"""Generate the gallery manifest from the category folders under assets/img.

Usage (from anywhere):
    python tools/update-gallery.py

What it does
    Scans assets/img/<category> folders and writes assets/data/gallery.js
    (a browser-ready manifest: window.DL_GALLERY = [...]).

Adding new media
    Drop files into the category folder, re-run this script, refresh the page.
    New folders are picked up only if listed in CATEGORIES below.

Supported media
    Images : .jpg .jpeg .png .webp .gif .avif .svg
    Videos : .mp4 .webm  (rendered with a play overlay and played in the lightbox)
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG = os.path.join(ROOT, "assets", "img")
OUT = os.path.join(ROOT, "assets", "data", "gallery.js")

# (folder name, manifest id, tab label)
CATEGORIES = [
    ("Surfing", "surfing", "Surfing"),
    ("Camp",    "camp",    "Camp Life"),
    ("Life",    "life",    "Life & Fun"),
    ("Rooms",   "rooms",   "Rooms"),
    ("Events",  "events",  "Events"),
    ("Videos",  "videos",  "Videos"),
]

IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif", ".svg"}
VIDEO_EXT = {".mp4", ".webm", ".mov", ".m4v"}


def humanize(name):
    """Turn a filename into a short caption ('dynamic_134.jpg' -> 'Dynamic 134')."""
    base = os.path.splitext(name)[0]
    base = base.replace("_", " ").replace("-", " ").strip()
    return base[:1].upper() + base[1:]


def main():
    categories = []
    for folder, cid, label in CATEGORIES:
        path = os.path.join(IMG, folder)
        if not os.path.isdir(path):
            continue
        files = []
        for f in sorted(os.listdir(path)):
            ext = os.path.splitext(f)[1].lower()
            if ext in IMAGE_EXT:
                mtype = "image"
            elif ext in VIDEO_EXT:
                mtype = "video"
            else:
                continue
            files.append({
                "src": "assets/img/%s/%s" % (folder, f),
                "name": humanize(f),
                "type": mtype,
            })
        categories.append({
            "id": cid,
            "label": label,
            "folder": folder,
            "files": files,
        })

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = (
        "/* Generated by tools/update-gallery.py - do not edit by hand.\n"
        "   Re-run the script after adding media to the category folders. */\n"
        "window.DL_GALLERY = " + json.dumps(categories, ensure_ascii=False, indent=2) + ";\n"
    )
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(body)

    total = sum(len(c["files"]) for c in categories)
    print("Wrote %s - %d media in %d categories" % (OUT, total, len(categories)))
    for c in categories:
        print("  %-9s %3d files" % (c["label"], len(c["files"])))


if __name__ == "__main__":
    main()